<program> 		::= <function> | <function> <program>
<function> 		::= '(' <fun_id_list> ')'
<fun_id_list> 	::= <fun_id> | <fun_id> <fun_id_list>
<fun_id> 		::= '(' <instr_list> ')' | 'fun' | 'method' | 'fun_arg'
<instr_list>	::=	<instr> | <instr> <instr_list>
<instr>			::= '(' <instr_id_list> ')'
<instr_id_list>	::= <instr_id> | <instr_id> <instr_id_list>
<instr_id>		::= <expr> | <res_instr_id> | 'instr_arg' | 'method_arg'
<res_instr_id>  ::= 'while' | 'else' | 'if' | 'return' | 'read' | 'write' | 'set' | 'endif' | 'endwhile' 
<expr>			::= '(' <expr_id_list> ')'
<expr_id_list>	::= <expr_id> | <expr_id> <expr_id_list>
<expr_id>		::= '+' | '-' | '*' | '/' | '%' | '<' | '>' | '=' | '<=' | '>=' | 'number' | 'expr_arg'