<l0_list>	::= <l0_instr> | <l0_instr> <l0_list> 
<l0_instr>	::= '(' <l0_instr_id_list> ')'
<l0_instr_id_list>	::= <l0_instr_id> | <l0_instr_id> <l0_instr_id_list> | '(' <l1_list> ')' 
<l0_instr_id>		::= <l0_expr> | 'l0_res_instr_id' | 'l0_instr_arg' 
<l0_expr>	::= '(' <l0_expr_id_list> ')' 
<l0_expr_id_list>	::= 'l0_expr_id' | 'l0_expr_id' <l0_expr_id_list>
<l1_list>	::= <l1_instr> | <l1_instr> <l1_list> 
<l1_instr>	::= '(' <l1_instr_id_list> ')'
<l1_instr_id_list>	::= <l1_instr_id> | <l1_instr_id> <l1_instr_id_list> | '(' <l2_list> ')' 
<l1_instr_id>		::= <l1_expr> | 'l1_res_instr_id' | 'l1_instr_arg' 
<l1_expr>	::= '(' <l1_expr_id_list> ')' 
<l1_expr_id_list>	::= 'l1_expr_id' | 'l1_expr_id' <l1_expr_id_list>
<l2_list>	::= <l2_instr> | <l2_instr> <l2_list> 
<l2_instr>	::= '(' <l2_instr_id_list> ')'
<l2_instr_id_list>	::= <l2_instr_id> | <l2_instr_id> <l2_instr_id_list> | '(' <l3_list> ')' 
<l2_instr_id>		::= <l2_expr> | 'l2_res_instr_id' | 'l2_instr_arg' 
<l2_expr>	::= '(' <l2_expr_id_list> ')' 
<l2_expr_id_list>	::= 'l2_expr_id' | 'l2_expr_id' <l2_expr_id_list>
<l3_list>	::= <l3_instr> | <l3_instr> <l3_list> 
<l3_instr>	::= '(' <l3_instr_id_list> ')'
<l3_instr_id_list>	::= <l3_instr_id> | <l3_instr_id> <l3_instr_id_list> 
<l3_instr_id>		::= <l3_expr> | 'l3_res_instr_id' | 'l3_instr_arg' 
<l3_expr>	::= '(' <l3_expr_id_list> ')' 
<l3_expr_id_list>	::= 'l3_expr_id' | 'l3_expr_id' <l3_expr_id_list>
