<number>		::=  <number> | 'pnumber'		
<meth_or_fun> 	::=  <method> | <function>
<Program> 		::=  <meth_or_fun> | <Program>  <meth_or_fun>
<function> 		::= '(' 'fun' '(' <arglist> ')' <instr_list> ')' 
<arglist> 		::=  <id> | <id> <arglist>
<methode> 		::= '(' 'method' '(' 'pnumber' ')' '(' <Name> <arglist> ')' <instr_list>  ')' | '(' 'method' '(' 'pnumber' ')' '(' <name> ')' <instr_list>  ')'
<instr_list> 	::=  <instr> | '(' <instr_list_np> ')' 
<instr_list_np> ::=  <instr> | <instr> <instr_list_np>
<instr> 		::=  <conditional> | <while_block> | <call> | '(' 'return' <expr> ')' | '(' 'skip' ')'
<conditional> 	::= '(' 'if' <expr> <instr_list> <instr_list>  ')' 
<while_block 	::= '(' 'while'  <expr>  <instr_list>  ')' 
<call> 			::=  <function_call> | <method_call> | <builtin_call> 
<builtin_call> 	::=  <assignment> | <read_call> | <write_call> | <arithmetic>
<assignment> 	::= '(' 'set' <id>  <expr> ')' | '(' 'set' <Id> '.' <expr> <expr> ')' | '(' 'set' 'this' '.' <expr> <expr> ')'
<read_call>  	::= '(' 'read' ')' 
<write_call> 	::= '(' 'write' <expr> ')'
<arithmetic> 	::=  <binary> | <unary>
<binary 		::= '(' 'bin_id'  <expr>  <expr>  ')'
<unary>  		::= '(' 'un_id'  <expr>  ')'
<user_call>  	::= '(' <Id>  <expr_list_np>  ')' | '('  <Id>  ')' 
<expr_list_np> 	::=  <expr> | <expr> <expr_list_np>
<method_call>  	::= '(' <Id>'.'<Id> <expr_list_np>  ')' |   '(' 'super''.'<Id><expr_list_np>  ')' 
<expr> 			::=  <call>  | <number> | 'null' | 'true' | 'false' | 'this' | <Id> | <Id>'.'<expr> | 'this'.<expr> 

