<l0> ::= <l0_block>  ')' | 'l0_id'
<l0_block> ::= '(' <l0_list>
<l0_list> ::= <l1> | <l1> <l0_list>
<l1> ::= <l1_block>  ')' | 'l1_id'
<l1_block> ::= '(' <l1_list>
<l1_list> ::= <l2> | <l2> <l1_list>
<l2> ::= <l2_block>  ')' | 'l2_id'
<l2_block> ::= '(' <l2_list>
<l2_list> ::= <l3> | <l3> <l2_list>
<l3> ::= <l3_block>  ')' | 'l3_id'
<l3_block> ::= '(' <l3_list>
<l3_list> ::= <l4> | <l4> <l3_list>
<l4> ::= <l4_block>  ')' | 'l4_id'
<l4_block> ::= '(' <l4_list>
<l4_list> ::= <l5> | <l5> <l4_list>
<l5> ::= <l5_block>  ')' | 'l5_id'
<l5_block> ::= '(' <l5_list>
<l5_list> ::= <l6> | <l6> <l5_list>
<l6> ::= <l6_block>  ')' | 'l6_id'
<l6_block> ::= '(' <l6_list>
<l6_list> ::= <l7> | <l7> <l6_list>
<l7> ::= <l7_block>  ')' | 'l7_id'
<l7_block> ::= '(' <l7_list>
<l7_list> ::= <l8> | <l8> <l7_list>
<l8> ::= <l8_block>  ')' | 'l8_id'
<l8_block> ::= '(' <l8_list>
<l8_list> ::= <l9> | <l9> <l8_list>
<l9> ::= <l9_block>  ')' | 'l9_id'
<l9_block> ::= '(' <l9_list>
<l9_list> ::= <l10> | <l10> <l9_list>
<l10> ::= <l10_block>  ')' | 'l10_id'
<l10_block> ::= '(' <l10_list>
<l10_list> ::= <l11> | <l11> <l10_list>
<l11> ::= <l11_block>  ')' | 'l11_id'
<l11_block> ::= '(' <l11_list>
<l11_list> ::= <l12> | <l12> <l11_list>
<l12> ::= <l12_block>  ')' | 'l12_id'
<l12_block> ::= '(' <l12_list>
<l12_list> ::= <l13> | <l13> <l12_list>
<l13> ::= <l13_block>  ')' | 'l13_id'
<l13_block> ::= '(' <l13_list>
<l13_list> ::= <l14> | <l14> <l13_list>
<l14> ::= <l14_block>  ')' | 'l14_id'
<l14_block> ::= '(' <l14_list>
<l14_list> ::= <l15> | <l15> <l14_list>
<l15> ::= <l15_block>  ')' | 'l15_id'
<l15_block> ::= '(' <l15_list>
<l15_list> ::= <l16> | <l16> <l15_list>
<l16> ::= <l16_block>  ')' | 'l16_id'
<l16_block> ::= '(' <l16_list>
<l16_list> ::= <l17> | <l17> <l16_list>
<l17> ::= <l17_block>  ')' | 'l17_id'
<l17_block> ::= '(' <l17_list>
<l17_list> ::= <l18> | <l18> <l17_list>
<l18> ::= <l18_block>  ')' | 'l18_id'
<l18_block> ::= '(' <l18_list>
<l18_list> ::= <l19> | <l19> <l18_list>
<l19> ::= <l19_block>  ')' | 'l19_id'
<l19_block> ::= '(' <l19_list>
<l19_list> ::= <l20> | <l20> <l19_list>
<l20> ::= 'l20_id'
